### ISSUE TITLE
Fails on some docker file

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#13]
Fails on some docker test files.  I'm not sure why.  Is it a symlink?

```
[2014-02-20 10:57:20][summershum    INFO] Ingesting u'docker-0.8.1.tar.gz'
[2014-02-20 10:57:22][summershum   ERROR] [Errno 2] No such file or directory: '/tmp/tmpadGgRA/docker-0.8.1/utils/testdata/fs/a/d'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/summershum/core.py", line 30, in ingest
    summershum.utils.calculate_sums(session, msg, tmpdir)
  File "/usr/lib/python2.6/site-packages/summershum/utils.py", line 64, in calculate_sums
    for fname, sha256sum, sha1sum, md5sum in walk_directory(filename):
  File "/usr/lib/python2.6/site-packages/summershum/utils.py", line 98, in walk_directory
    with open(file_path) as stream:
IOError: [Errno 2] No such file or directory: '/tmp/tmpadGgRA/docker-0.8.1/utils/testdata/fs/a/d'
[2014-02-20 10:57:22][summershum   ERROR] Failed to ingest u'docker-0.8.1.tar.gz' IOError(2, 'No such file or directory')
```

**Comment by pypingou** [comment]
taking this one

**Comment by pypingou** [comment]
Sources concerned: http://pkgs.fedoraproject.org/lookaside/pkgs/docker-io/docker-0.8.1.tar.gz/3e74f5af4a74f3448a1db5763e455eb9/
