### ISSUE TITLE
Failed on rubik

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#14]
Saw this in the logs

```
[2014-02-20 19:40:27][summershum   ERROR] [Errno 2] No such file or directory: '/tmp/tmpb4Ws76/bin/i386-linux/rubikrotation'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/summershum/core.py", line 30, in ingest
    summershum.utils.calculate_sums(session, msg, tmpdir)
  File "/usr/lib/python2.6/site-packages/summershum/utils.py", line 64, in calculate_sums
    for fname, sha256sum, sha1sum, md5sum in walk_directory(filename):
  File "/usr/lib/python2.6/site-packages/summershum/utils.py", line 98, in walk_directory
    with open(file_path) as stream:
IOError: [Errno 2] No such file or directory: '/tmp/tmpb4Ws76/bin/i386-linux/rubikrotation'
```

**Comment by pypingou** [comment]
Do we have the previous log entry, the name of the package?

**Comment by ralphbean** [comment]
Works now.
