### ISSUE TITLE
Trouble with git-htmldocs-1.9.0.tar.gz

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#5]
summershum chokes on this one:

```
[2014-02-18 14:40:23][summershum    INFO] Ingesting u'git-htmldocs-1.9.0.tar.gz'
[2014-02-18 14:40:37][summershum   ERROR] [Errno 22] Invalid argument: 'downloads/.'
Traceback (most recent call last):
  File "/home/threebean/devel/summershum/summershum/core.py", line 26, in ingest
    summershum.utils.calculate_sums(session, msg, tmpdir)
  File "/home/threebean/devel/summershum/summershum/utils.py", line 85, in calculate_sums
    shutil.rmtree(filename)
  File "/usr/lib64/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib64/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: 'downloads/.'
```

**Comment by pypingou** [comment]
`.` is a nasty one

**Comment by pypingou** [comment]
looking at the content of this tarball (`git` package), it is indeed `./<file>`

**Comment by pypingou** [comment]
I think https://github.com/fedora-infra/summershum/pull/7 should fix this
