### ISSUE TITLE
Fails on qpid tarball

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/summershum#9]
Saw this in the logs:

```
[2014-02-20 10:48:37][summershum   ERROR] [Errno 2] No such file or directory: '/tmp/tmpsfPvQM/qpid-0.26/extras/sasl/build-aux/py-compile'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/summershum/core.py", line 30, in ingest
    summershum.utils.calculate_sums(session, msg, tmpdir)
  File "/usr/lib/python2.6/site-packages/summershum/utils.py", line 64, in calculate_sums
    for fname, sha256sum, sha1sum, md5sum in walk_directory(filename):
  File "/usr/lib/python2.6/site-packages/summershum/utils.py", line 98, in walk_directory
    with open(file_path) as stream:
IOError: [Errno 2] No such file or directory: '/tmp/tmpsfPvQM/qpid-0.26/extras/sasl/build-aux/py-compile'
[2014-02-20 10:48:37][summershum   ERROR] Failed to ingest u'qpid-0.26.tar.gz' IOError(2, 'No such file or directory')
```

**Comment by pypingou** [comment]
taking this one

**Comment by pypingou** [comment]
This seems to be the one of concerns http://pkgs.fedoraproject.org/lookaside/pkgs/qpid-cpp/qpid-0.26.tar.gz/31c4a058654c91f28ad6bfdcb0e7371e/

**Comment by ralphbean** [comment]
This is fixed now (It was a symlink).
